### ISSUE TITLE
Not getting latest fixes via composer install

### ISSUE THREAD

**Issue by francesko** [toni-kolev/MultilingualExtension#5]
Hi @toni-kolev, I am installing this package via composer, but I do not get the fixes you made to languages_iso_codes.json. Could you please create a new version for that?

**Comment by toni-kolev** [comment]
Hello @francesko ,

are you sure you are downloading master branch as there are some commits after latest release.

I'm using `"kolev/multilingual-extension": "dev-master"` in my `composer.json` and I got all changes.

**Comment by alexiusp** [comment]
Hello @toni-kolev,

for me it does not work too. I have ran a `composer clearcache` command and have dev-master as a dependency, but composer still installs version 0.0.2 which is wrong.

UPD: Sorry, I've forgot to delete the composer.lock file. Now it works! @francesko you should check if you have also forgot to do something like this.

**Comment by toni-kolev** [comment]
@alexiusp glad you figured it out.

If you have any other issues or improvement ideas, let me know.

**Comment by francesko** [comment]
Great, thanks for your help guys @toni-kolev @alexiusp
